import PFEntity from '../entities/pf.entity';
import ReservationEntity from '../entities/reservation.entity';
import RoomEntity from '../entities/room.entity';
import UserEntity from '../entities/user.entity';

export default class Database {
  data: { [key: string]: any[] };
  private static instance: Database;

  private constructor() {
    this.data = {};
  }

  static getInstance() {
    if (!Database.instance) {
      Database.instance = new Database();
    }
    return Database.instance;
  }

  static reset() {
    Database.instance = new Database();
  }

  static seed() {
    Database.getInstance().data = {
      reservations: [
        new ReservationEntity({
          id: '1',
          pf_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          room_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1c',
          check_in: new Date('2025-03-09'),
          check_out: new Date('2025-03-29'),
          guests: 2,
          total: 100,
          status: 'Pending',
          rating: { stars: 0, comment: '' },
        }),
      ],
      rooms: [
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1c',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1d',
          description: 'Quarto a Beira Mar',
          price: 100,
          type: 'Suíte',
          capacity: 2,
          caracteristics_ids: ['Cuidado com os Tubarões'],
          local: 'Recife',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: false,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1a',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          description: 'Beach Class Santa Maria',
          price: 300,
          type: 'Apt 701',
          capacity: 2,
          caracteristics_ids: ['Danilo'],
          local: 'Recife',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: false,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          description: 'Quarto dos Tubas',
          price: 200,
          type: 'Praia', // Seed, Standard, Premium
          capacity: 2,
          caracteristics_ids: ['muitos tubarões'],
          local: 'Recife',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1e',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          description: 'Evolution',
          price: 400,
          type: 'Cobertura',
          capacity: 2,
          caracteristics_ids: ['Marsaro de brinde'],
          local: 'Recife',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: false,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'cairo-001',
          pj_id: 'pj-cairo-001',
          description: 'Quarto Deluxe - Nile View Hotel',
          price: 520,
          type: 'Deluxe',
          capacity: 2,
          caracteristics_ids: ['Deluxe', 'Vista para o Nilo'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.7,
        }),
        
        new RoomEntity({
          id: 'cairo-002',
          pj_id: 'pj-cairo-002',
          description: 'Suíte Real - Pharaoh Palace',
          price: 850,
          type: 'Suíte',
          capacity: 3,
          caracteristics_ids: ['Suíte', 'Banheira', 'Vista para pirâmides'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5,
        }),
        
        new RoomEntity({
          id: 'cairo-003',
          pj_id: 'pj-cairo-003',
          description: 'Flat Econômico - Cairo Central Inn',
          price: 210,
          type: 'Econômico',
          capacity: 2,
          caracteristics_ids: ['Flat'],
          local: 'Cairo',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: false,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 3.8,
        }),

        new RoomEntity({
          id: 'cairo-022',
          pj_id: 'pj-cairo-022',
          description: 'Flat Business - Cairo Central Inn',
          price: 210,
          type: 'Executivo',
          capacity: 5,
          caracteristics_ids: ['Flat'],
          local: 'Cairo',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 4.8,
        }),
        
        new RoomEntity({
          id: 'cairo-004',
          pj_id: 'pj-cairo-004',
          description: 'Chalé Egípcio - Oasis Retreat',
          price: 480,
          type: 'Chalé',
          capacity: 4,
          caracteristics_ids: ['Chalé', 'Varanda'],
          local: 'Cairo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.5,
        }),
        
        new RoomEntity({
          id: 'cairo-005',
          pj_id: 'pj-cairo-005',
          description: 'Quarto Executivo - Business Tower Hotel',
          price: 390,
          type: 'Executivo',
          capacity: 1,
          caracteristics_ids: ['Escrivaninha', 'Business'],
          local: 'Cairo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.1,
        }),
        
        new RoomEntity({
          id: 'cairo-006',
          pj_id: 'pj-cairo-006',
          description: 'Suíte Familiar - Desert Pearl Hotel',
          price: 610,
          type: 'Familiar',
          capacity: 5,
          caracteristics_ids: ['Familiar', 'Cozinha'],
          local: 'Cairo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.6,
        }),
        
        new RoomEntity({
          id: 'cairo-007',
          pj_id: 'pj-cairo-007',
          description: 'Acomodação Boutique - Sphinx Boutique Hotel',
          price: 470,
          type: 'Boutique',
          capacity: 2,
          caracteristics_ids: ['Boutique', 'Design exclusivo'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'cairo-008',
          pj_id: 'pj-cairo-008',
          description: 'Estúdio Moderno - The Cairo Spot',
          price: 330,
          type: 'Estúdio',
          capacity: 2,
          caracteristics_ids: ['Moderno', 'Minimalista'],
          local: 'Cairo',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.0,
        }),
        
        new RoomEntity({
          id: 'cairo-009',
          pj_id: 'pj-cairo-009',
          description: 'Tenda Luxuosa - Desert Luxury Camp',
          price: 700,
          type: 'Tenda',
          capacity: 2,
          caracteristics_ids: ['Luxo', 'Experiência no deserto'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.7,
        }),
        
        new RoomEntity({
          id: 'cairo-010',
          pj_id: 'pj-cairo-010',
          description: 'Quarto Simples - Hostel das Areias',
          price: 150,
          type: 'Simples',
          capacity: 1,
          caracteristics_ids: ['Econômico'],
          local: 'Cairo',
          stars: 2,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 3.5,
        }),        
        new RoomEntity({
          id: 'a1b2c3d4-1111-2222-3333-444455556666',
          pj_id: 'z9y8x7w6-aaaa-bbbb-cccc-ddddeeeeffff',
          description: 'Suíte Luxo - Hotel Mar Azul',
          price: 620,
          type: 'Deluxe',
          capacity: 3,
          caracteristics_ids: ['Deluxe', 'Vista para o mar'],
          local: 'Fernando de Noronha',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'b2c3d4e5-7777-8888-9999-aaaabbbbcccc',
          pj_id: 'y7x6w5v4-zzzz-yyyy-xxxx-wwwwvvvvuuuu',
          description: 'Quarto Executivo - Hotel Aurora',
          price: 350,
          type: 'Executivo',
          capacity: 2,
          caracteristics_ids: ['Executivo', 'Escrivaninha'],
          local: 'São Paulo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 4.5,
        }),
        
        new RoomEntity({
          id: 'c3d4e5f6-3333-4444-5555-666677778888',
          pj_id: 'w6v5u4t3-pppp-qqqq-rrrr-ssssttttuuuu',
          description: 'Cabana Rústica - Pousada Bosque Verde',
          price: 280,
          type: 'Cabana',
          capacity: 2,
          caracteristics_ids: ['Rústico', 'Vista para natureza'],
          local: 'Gramado',
          stars: 3,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.0,
        }),
        
        new RoomEntity({
          id: 'd4e5f6g7-5555-6666-7777-88889999aaaa',
          pj_id: 't3s2r1q0-kkkk-llll-mmmm-nnnnoooopppp',
          description: 'Flat Urbano - Urban Stay Hotel',
          price: 410,
          type: 'Flat',
          capacity: 2,
          caracteristics_ids: ['Flat', 'Cozinha completa'],
          local: 'Curitiba',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.3,
        }),
        
        new RoomEntity({
          id: 'e5f6g7h8-9999-aaaa-bbbb-ccccddddeeee',
          pj_id: 'r0q9p8o7-nnnn-oooo-pppp-qqqqrrrrssss',
          description: 'Chalé Premium - Montanha Serena Resort',
          price: 700,
          type: 'Chalé',
          capacity: 4,
          caracteristics_ids: ['Chalé', 'Lareira', 'Banheira'],
          local: 'Campos do Jordão',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.8,
        }),

        new RoomEntity({
          id: 'sp-001',
          pj_id: 'pj-sp-001',
          description: 'Suíte Executiva - Hotel Paulista Center',
          price: 480,
          type: 'Suíte',
          capacity: 2,
          caracteristics_ids: ['Moderno', 'Escritório'],
          local: 'São Paulo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.6,
        }),
        
        new RoomEntity({
          id: 'sp-002',
          pj_id: 'pj-sp-002',
          description: 'Studio Aconchegante - Vila Madalena Flat',
          price: 310,
          type: 'Studio',
          capacity: 2,
          caracteristics_ids: ['Cozinha', 'Varanda'],
          local: 'São Paulo',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 4.2,
        }),
        
        new RoomEntity({
          id: 'sp-003',
          pj_id: 'pj-sp-003',
          description: 'Flat Luxo - Jardins Premium',
          price: 620,
          type: 'Flat',
          capacity: 3,
          caracteristics_ids: ['Banheira', 'Vista da cidade'],
          local: 'São Paulo',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'sp-004',
          pj_id: 'pj-sp-004',
          description: 'Quarto Econômico - Hostel Liberdade',
          price: 180,
          type: 'Simples',
          capacity: 1,
          caracteristics_ids: ['Econômico'],
          local: 'São Paulo',
          stars: 2,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 3.8,
        }),
        new RoomEntity({
          id: 'sp-005',
          pj_id: 'pj-sp-005',
          description: 'Apartamento Familiar - Brooklin Stay',
          price: 540,
          type: 'Apartamento',
          capacity: 5,
          caracteristics_ids: ['Familiar', 'Cozinha completa'],
          local: 'São Paulo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.4,
        }),
        new RoomEntity({
          id: 'paris-001',
          pj_id: 'pj-paris-001',
          description: 'Suíte Romântica - Eiffel Charm Hotel',
          price: 850,
          type: 'Suíte',
          capacity: 2,
          caracteristics_ids: ['Vista Torre Eiffel', 'Luxo'],
          local: 'Paris',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'paris-002',
          pj_id: 'pj-paris-002',
          description: 'Studio Artístico - Quartier Latin',
          price: 420,
          type: 'Studio',
          capacity: 2,
          caracteristics_ids: ['Artístico', 'Bairro boêmio'],
          local: 'Paris',
          stars: 3,
          ar_condicionado: false,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 4.3,
        }),
        
        new RoomEntity({
          id: 'paris-003',
          pj_id: 'pj-paris-003',
          description: 'Apartamento Charmoso - Marais Boutique',
          price: 560,
          type: 'Apartamento',
          capacity: 3,
          caracteristics_ids: ['Charmoso', 'Histórico'],
          local: 'Paris',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 4.5,
        }),
        
        new RoomEntity({
          id: 'paris-004',
          pj_id: 'pj-paris-004',
          description: 'Quarto Econômico - Paris Budget Inn',
          price: 250,
          type: 'Simples',
          capacity: 1,
          caracteristics_ids: ['Básico'],
          local: 'Paris',
          stars: 2,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 3.9,
        }),
        
        new RoomEntity({
          id: 'paris-005',
          pj_id: 'pj-paris-005',
          description: 'Cobertura Luxuosa - Seine River View',
          price: 980,
          type: 'Cobertura',
          capacity: 4,
          caracteristics_ids: ['Vista rio', 'Banheira'],
          local: 'Paris',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5.0,
        }),

        new RoomEntity({
          id: 'london-001',
          pj_id: 'pj-london-001',
          description: 'Flat Urbano - London Bridge Suites',
          price: 600,
          type: 'Flat',
          capacity: 2,
          caracteristics_ids: ['Vista cidade', 'Moderno'],
          local: 'Londres',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 4.7,
        }),
        
        new RoomEntity({
          id: 'london-002',
          pj_id: 'pj-london-002',
          description: 'Suíte Clássica - The Royal Garden Hotel',
          price: 880,
          type: 'Suíte',
          capacity: 3,
          caracteristics_ids: ['Luxo', 'Clássico'],
          local: 'Londres',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'london-003',
          pj_id: 'pj-london-003',
          description: 'Quarto Aconchegante - Camden Town Inn',
          price: 350,
          type: 'Quarto',
          capacity: 2,
          caracteristics_ids: ['Descolado', 'Minimalista'],
          local: 'Londres',
          stars: 3,
          ar_condicionado: false,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 4.1,
        }),
        
        new RoomEntity({
          id: 'london-004',
          pj_id: 'pj-london-004',
          description: 'Apartamento Familiar - Hyde Park Residences',
          price: 670,
          type: 'Apartamento',
          capacity: 5,
          caracteristics_ids: ['Familiar', 'Cozinha'],
          local: 'Londres',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.6,
        }),
        
        new RoomEntity({
          id: 'london-005',
          pj_id: 'pj-london-005',
          description: 'Estúdio Moderno - Notting Hill Studio',
          price: 410,
          type: 'Studio',
          capacity: 2,
          caracteristics_ids: ['Bairro charmoso', 'Decoração moderna'],
          local: 'Londres',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 4.3,
        }),
        new RoomEntity({
          id: 'toronto-001',
          pj_id: 'pj-toronto-001',
          description: 'Suíte Panorâmica - CN Tower View Hotel',
          price: 720,
          type: 'Suíte',
          capacity: 2,
          caracteristics_ids: ['Vista panorâmica', 'Luxo'],
          local: 'Toronto',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'toronto-002',
          pj_id: 'pj-toronto-002',
          description: 'Studio Compacto - Downtown Stay',
          price: 320,
          type: 'Studio',
          capacity: 2,
          caracteristics_ids: ['Moderno', 'Localização central'],
          local: 'Toronto',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 4.1,
        }),
        
        new RoomEntity({
          id: 'toronto-003',
          pj_id: 'pj-toronto-003',
          description: 'Apartamento Familiar - Queen Street Flats',
          price: 580,
          type: 'Apartamento',
          capacity: 5,
          caracteristics_ids: ['Familiar', 'Cozinha completa'],
          local: 'Toronto',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.5,
        }),
        
        new RoomEntity({
          id: 'toronto-004',
          pj_id: 'pj-toronto-004',
          description: 'Quarto Econômico - Toronto Budget Inn',
          price: 210,
          type: 'Quarto',
          capacity: 1,
          caracteristics_ids: ['Econômico'],
          local: 'Toronto',
          stars: 2,
          ar_condicionado: false,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 3.7,
        }),
        
        new RoomEntity({
          id: 'toronto-005',
          pj_id: 'pj-toronto-005',
          description: 'Loft Industrial - Urban Design Hotel',
          price: 460,
          type: 'Loft',
          capacity: 2,
          caracteristics_ids: ['Estilo industrial', 'Decoração moderna'],
          local: 'Toronto',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.4,
        }),
        new RoomEntity({
          id: 'nyc-001',
          pj_id: 'pj-nyc-001',
          description: 'Suíte Luxo - Manhattan Palace',
          price: 920,
          type: 'Suíte',
          capacity: 2,
          caracteristics_ids: ['Luxo', 'Vista para cidade'],
          local: 'Nova York',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5.0,
        }),
        new RoomEntity({
          id: 'orlando-001',
          pj_id: 'pj-orlando-001',
          description: 'Resort Familiar - Magical Stay',
          price: 650,
          type: 'Resort',
          capacity: 6,
          caracteristics_ids: ['Familiar', 'Perto da Disney'],
          local: 'Orlando',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5.0,
        }),
        
        new RoomEntity({
          id: 'orlando-002',
          pj_id: 'pj-orlando-002',
          description: 'Suíte Temática - Wizard World Hotel',
          price: 540,
          type: 'Suíte',
          capacity: 4,
          caracteristics_ids: ['Temática', 'Ideal para crianças', 'Ideal para o seu Pet'],
          local: 'Orlando',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.7,
        }),
        
        new RoomEntity({
          id: 'orlando-003',
          pj_id: 'pj-orlando-003',
          description: 'Apartamento Econômico - Orlando Easy Inn',
          price: 290,
          type: 'Apartamento',
          capacity: 3,
          caracteristics_ids: ['Econômico'],
          local: 'Orlando',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.0,
        }),
        
        new RoomEntity({
          id: 'orlando-004',
          pj_id: 'pj-orlando-004',
          description: 'Villa Privativa - Sunny Retreat Villas',
          price: 820,
          type: 'Villa',
          capacity: 6,
          caracteristics_ids: ['Piscina privativa', 'Luxo'],
          local: 'Orlando',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.8,
        }),
        
        new RoomEntity({
          id: 'orlando-005',
          pj_id: 'pj-orlando-005',
          description: 'Studio Moderno - International Drive Stay',
          price: 370,
          type: 'Studio',
          capacity: 2,
          caracteristics_ids: ['Moderno', 'Próximo a outlets'],
          local: 'Orlando',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.3,
        }),

        new RoomEntity({
          id: 'rio-001',
          pj_id: 'pj-rio-001',
          description: 'Suíte Luxo - Copacabana Palace',
          price: 720,
          type: 'Suíte',
          capacity: 2,
          caracteristics_ids: ['Luxo', 'Vista para o mar'],
          local: 'Rio de Janeiro',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
      ],
      tests: [
        // new TestEntity({
        //   id: '89ecc32a-aec7-4b71-adfd-03287e4ca74f',
        //   name: 'Test Seed',
        //   cpf: '8888',
        // }),
      ],
      users: [
        new UserEntity({
          id: '12732',
          email:'bia@example.com',
          password:'123',
          type:'pf'
        }),
        new UserEntity({
          id: '12733',  
          email: 'lfla@cin.ufpe.br',
          password: 'lily123',
          type: 'pf',
        }),
      ],
      pfs: [
        new PFEntity({
          id: '12732',
          user_id: '1',
          name: 'bia',
          birth_date: new Date(2000, 0, 9),
          cpf: '28173891',
          phone: '98171-2882',
          favorites: ['f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1e', 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1a'],
          savedRooms: ['f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1e'],
        }),
        new PFEntity({
          id: '12733',
          user_id: '2',
          name: 'lulu',
          birth_date: new Date(2003, 11, 22),
          cpf: '28173892',
          phone: '98171-2883',
          favorites: ['f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1e', 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1a', 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b', 'nyc-001'],
          savedRooms: ['toronto-005', 'orlando-005', 'london-005', 'paris-005', 'cairo-005'],
        }),
      
      ],
      // tests: [
      //   new TestEntity({
      //     id: '89ecc32a-aec7-4b71-adfd-03287e4ca74f',
      //     name: 'Test Seed',
      //     cpf: '8888',
      //   }),
      //],
    };
  }
}
