import PFEntity from '../entities/pf.entity';
import ReservationEntity from '../entities/reservation.entity';
import RoomEntity from '../entities/room.entity';

export default class Database {
  data: { [key: string]: any[] };
  private static instance: Database;

  private constructor() {
    this.data = {};
  }

  static getInstance() {
    if (!Database.instance) {
      Database.instance = new Database();
    }
    return Database.instance;
  }

  static reset() {
    Database.instance = new Database();
  }

  static seed() {
    Database.getInstance().data = {
      reservations: [
        new ReservationEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1a',
          pf_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          room_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1a',
          check_in: new Date('2025-03-09'),
          check_out: new Date('2025-03-29'),
          guests: 2,
          total: 100,
          status: 'Pending',
          rating: { stars: 0, comment: '' },
        }),
      ],
      rooms: [
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1c',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1d',
          description: 'Room Seed',
          price: 100,
          type: 'Seed',
          capacity: 2,
          caracteristics_ids: ['Seed'],
          local: 'Recife',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: false,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1a',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          description: 'Room 1',
          price: 300,
          type: 'Seed',
          capacity: 2,
          caracteristics_ids: ['Seed'],
          local: 'Recife',
          stars: 5,
          ar_condicionado: false,
          tv: true,
          wifi: false,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          description: 'Room 2',
          price: 200,
          type: 'Seed', // Seed, Standard, Premium
          capacity: 2,
          caracteristics_ids: ['Seed'],
          local: 'Recife',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1e',
          pj_id: 'f5b0e3d2-4b6f-4d8f-8f5a-7b1a5b2f8a1b',
          description: 'Room 3',
          price: 400,
          type: 'Seed',
          capacity: 2,
          caracteristics_ids: ['Seed'],
          local: 'Recife',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: false,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5,
        }),
        new RoomEntity({
          id: 'cairo-001',
          pj_id: 'pj-cairo-001',
          description: 'Quarto Deluxe - Nile View Hotel',
          price: 520,
          type: 'Deluxe',
          capacity: 2,
          caracteristics_ids: ['Deluxe', 'Vista para o Nilo'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.7,
        }),
        
        new RoomEntity({
          id: 'cairo-002',
          pj_id: 'pj-cairo-002',
          description: 'Suíte Real - Pharaoh Palace',
          price: 850,
          type: 'Suíte',
          capacity: 3,
          caracteristics_ids: ['Suíte', 'Banheira', 'Vista para pirâmides'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 5,
        }),
        
        new RoomEntity({
          id: 'cairo-003',
          pj_id: 'pj-cairo-003',
          description: 'Flat Econômico - Cairo Central Inn',
          price: 210,
          type: 'Econômico',
          capacity: 2,
          caracteristics_ids: ['Flat'],
          local: 'Cairo',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: false,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 3.8,
        }),

        new RoomEntity({
          id: 'cairo-022',
          pj_id: 'pj-cairo-022',
          description: 'Flat Business - Cairo Central Inn',
          price: 210,
          type: 'Executivo',
          capacity: 5,
          caracteristics_ids: ['Flat'],
          local: 'Cairo',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 4.8,
        }),
        
        new RoomEntity({
          id: 'cairo-004',
          pj_id: 'pj-cairo-004',
          description: 'Chalé Egípcio - Oasis Retreat',
          price: 480,
          type: 'Chalé',
          capacity: 4,
          caracteristics_ids: ['Chalé', 'Varanda'],
          local: 'Cairo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.5,
        }),
        
        new RoomEntity({
          id: 'cairo-005',
          pj_id: 'pj-cairo-005',
          description: 'Quarto Executivo - Business Tower Hotel',
          price: 390,
          type: 'Executivo',
          capacity: 1,
          caracteristics_ids: ['Escrivaninha', 'Business'],
          local: 'Cairo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.1,
        }),
        
        new RoomEntity({
          id: 'cairo-006',
          pj_id: 'pj-cairo-006',
          description: 'Suíte Familiar - Desert Pearl Hotel',
          price: 610,
          type: 'Familiar',
          capacity: 5,
          caracteristics_ids: ['Familiar', 'Cozinha'],
          local: 'Cairo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.6,
        }),
        
        new RoomEntity({
          id: 'cairo-007',
          pj_id: 'pj-cairo-007',
          description: 'Acomodação Boutique - Sphinx Boutique Hotel',
          price: 470,
          type: 'Boutique',
          capacity: 2,
          caracteristics_ids: ['Boutique', 'Design exclusivo'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'cairo-008',
          pj_id: 'pj-cairo-008',
          description: 'Estúdio Moderno - The Cairo Spot',
          price: 330,
          type: 'Estúdio',
          capacity: 2,
          caracteristics_ids: ['Moderno', 'Minimalista'],
          local: 'Cairo',
          stars: 3,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.0,
        }),
        
        new RoomEntity({
          id: 'cairo-009',
          pj_id: 'pj-cairo-009',
          description: 'Tenda Luxuosa - Desert Luxury Camp',
          price: 700,
          type: 'Tenda',
          capacity: 2,
          caracteristics_ids: ['Luxo', 'Experiência no deserto'],
          local: 'Cairo',
          stars: 5,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.7,
        }),
        
        new RoomEntity({
          id: 'cairo-010',
          pj_id: 'pj-cairo-010',
          description: 'Quarto Simples - Hostel das Areias',
          price: 150,
          type: 'Simples',
          capacity: 1,
          caracteristics_ids: ['Econômico'],
          local: 'Cairo',
          stars: 2,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: false,
          avaliacao: 3.5,
        }),        
        new RoomEntity({
          id: 'a1b2c3d4-1111-2222-3333-444455556666',
          pj_id: 'z9y8x7w6-aaaa-bbbb-cccc-ddddeeeeffff',
          description: 'Suíte Luxo - Hotel Mar Azul',
          price: 620,
          type: 'Deluxe',
          capacity: 3,
          caracteristics_ids: ['Deluxe', 'Vista para o mar'],
          local: 'Fernando de Noronha',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.9,
        }),
        
        new RoomEntity({
          id: 'b2c3d4e5-7777-8888-9999-aaaabbbbcccc',
          pj_id: 'y7x6w5v4-zzzz-yyyy-xxxx-wwwwvvvvuuuu',
          description: 'Quarto Executivo - Hotel Aurora',
          price: 350,
          type: 'Executivo',
          capacity: 2,
          caracteristics_ids: ['Executivo', 'Escrivaninha'],
          local: 'São Paulo',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: true,
          estacionamento: false,
          avaliacao: 4.5,
        }),
        
        new RoomEntity({
          id: 'c3d4e5f6-3333-4444-5555-666677778888',
          pj_id: 'w6v5u4t3-pppp-qqqq-rrrr-ssssttttuuuu',
          description: 'Cabana Rústica - Pousada Bosque Verde',
          price: 280,
          type: 'Cabana',
          capacity: 2,
          caracteristics_ids: ['Rústico', 'Vista para natureza'],
          local: 'Gramado',
          stars: 3,
          ar_condicionado: false,
          tv: false,
          wifi: true,
          petFriendly: true,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.0,
        }),
        
        new RoomEntity({
          id: 'd4e5f6g7-5555-6666-7777-88889999aaaa',
          pj_id: 't3s2r1q0-kkkk-llll-mmmm-nnnnoooopppp',
          description: 'Flat Urbano - Urban Stay Hotel',
          price: 410,
          type: 'Flat',
          capacity: 2,
          caracteristics_ids: ['Flat', 'Cozinha completa'],
          local: 'Curitiba',
          stars: 4,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: false,
          cafeDaManha: false,
          estacionamento: true,
          avaliacao: 4.3,
        }),
        
        new RoomEntity({
          id: 'e5f6g7h8-9999-aaaa-bbbb-ccccddddeeee',
          pj_id: 'r0q9p8o7-nnnn-oooo-pppp-qqqqrrrrssss',
          description: 'Chalé Premium - Montanha Serena Resort',
          price: 700,
          type: 'Chalé',
          capacity: 4,
          caracteristics_ids: ['Chalé', 'Lareira', 'Banheira'],
          local: 'Campos do Jordão',
          stars: 5,
          ar_condicionado: true,
          tv: true,
          wifi: true,
          petFriendly: true,
          cafeDaManha: true,
          estacionamento: true,
          avaliacao: 4.8,
        }),
        
      ],
      tests: [
        // new TestEntity({
        //   id: '89ecc32a-aec7-4b71-adfd-03287e4ca74f',
        //   name: 'Test Seed',
        //   cpf: '8888',
        // }),
      ],
      pfs: [
        new PFEntity({
          id: '12732',
          user_id: '1',
          name: 'bia',
          birth_date: new Date(2000, 0, 9),
          cpf: '28173891',
          phone: '98171-2882',
          favorites: ['12', '22', '32'],
          savedRooms: ['12', '222', '32'],
        }),
      ],
      // tests: [
      //   new TestEntity({
      //     id: '89ecc32a-aec7-4b71-adfd-03287e4ca74f',
      //     name: 'Test Seed',
      //     cpf: '8888',
      //   }),
      //],
    };
  }
}
