import type { Location, Reservation, Reservation2, Room } from "@/components/types/interface"

export const locations: Location[] = [
  {
    id: "e121",
    name: "CIn - Sala E121",
    address: "Av. Jornalista Aníbal Fernandes, s/n - Cidade Universitária, Recife, PE, Pernambuco",
    rating: 10,
    stars: 5,
    reservations: 10,
    dailyRate: 250.0,
  },
  {
    id: "e122",
    name: "CIn - Sala E122",
    address: "Av. Jornalista Aníbal Fernandes, s/n - Cidade Universitária, Recife, PE, Pernambuco",
    rating: 10,
    stars: 5,
    reservations: 10,
    dailyRate: 230.0,
  },
  {
    id: "e123",
    name: "CIn - Sala E123",
    address: "Av. Jornalista Aníbal Fernandes, s/n - Cidade Universitária, Recife, PE, Pernambuco",
    rating: 10,
    stars: 5,
    reservations: 10,
    dailyRate: 245.0,
  },
  {
    id: "e111",
    name: "CIn - Sala E111",
    address: "Av. Jornalista Aníbal Fernandes, s/n - Cidade Universitária, Recife, PE, Pernambuco",
    rating: 10,
    stars: 5,
    reservations: 10,
    dailyRate: 220.0,
  },
]

export const reservations2: Reservation2[] = [
  {
    id: "res1",
    guestName: "Alexandre Silva",
    startDate: "03/03/2025",
    endDate: "08/03/2025",
    guestCount: 2,
    price: 1145.39,
    locationId: "e122",
    imageUrl: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "res2",
    guestName: "Humberta Guimarães",
    startDate: "12/03/2025",
    endDate: "15/03/2025",
    guestCount: 1,
    price: 452.58,
    locationId: "e122",
    imageUrl: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "res3",
    guestName: "Rogério Severino",
    startDate: "20/03/2025",
    endDate: "22/03/2025",
    guestCount: 2,
    price: 320.45,
    locationId: "e122",
    imageUrl: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "res4",
    guestName: "Maria Santos",
    startDate: "05/03/2025",
    endDate: "10/03/2025",
    guestCount: 3,
    price: 1250.0,
    locationId: "e121",
    imageUrl: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "res5",
    guestName: "João Pereira",
    startDate: "15/03/2025",
    endDate: "20/03/2025",
    guestCount: 2,
    price: 980.75,
    locationId: "e123",
    imageUrl: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "res6",
    guestName: "Carla Oliveira",
    startDate: "01/04/2025",
    endDate: "05/04/2025",
    guestCount: 1,
    price: 750.3,
    locationId: "e111",
    imageUrl: "/placeholder.svg?height=150&width=150",
  },
]

const roomsFallbackData: Room[] = [
  {
    id: "101",
    pj_id: "PJ001",
    description: "CIn - Sala E121",
    type: "Conferência",
    price: 200,
    capacity: 50,
    caracteristics_ids: ["wifi", "ar_condicionado", "projetor"],
    local: "Recife",
    stars: 5,
    ar_condicionado: true,
    tv: false,
    wifi: true,
    petFriendly: false,
    cafeDaManha: false,
    estacionamento: true,
    avaliacao: 4.8,
  },
  {
    id: "102",
    pj_id: "PJ002",
    description: "CIn - Sala E122",
    type: "Padrão",
    price: 100,
    capacity: 20,
    caracteristics_ids: ["wifi", "tv"],
    local: "Recife",
    stars: 4,
    ar_condicionado: false,
    tv: true,
    wifi: true,
    petFriendly: false,
    cafeDaManha: false,
    estacionamento: false,
    avaliacao: 4.2,
  },
]

const reservationFallbackData: Reservation[] = [
  {
    id: "101",
    pf_id: "Jorge",
    room_id: "101",
    check_in: new Date("2025-03-20"),
    check_out: new Date("2025-03-22"),
    guests: 1,
    total: 103.59,
    status: "Confirmada",
    rating: { stars: 5, comment: "Ótima estadia" },
  },
  {
    id: "102",
    pf_id: "Antonia",
    room_id: "102",
    check_in: new Date("2025-03-26"),
    check_out: new Date("2025-03-30"),
    guests: 2,
    total: 457.90,
    status: "Confirmada",
    rating: { stars: 4, comment: "Muito bom" },
  },
]

export const reservationsFallbackData: [Reservation, Room][] = [ 
  [
    {
      id: "1",
      pf_id: "Joana",
      room_id: "101",
      check_in: new Date("2025-03-20"),
      check_out: new Date("2025-03-22"),
      guests: 1,
      total: 103.59,
      status: "Confirmada",
      rating: { stars: 5, comment: "Ótima estadia" },
    },
    {
      id: "101",
      pj_id: "PJ001",
      description: "CIn - Sala E121",
      type: "Conferência",
      price: 200,
      capacity: 50,
      caracteristics_ids: ["wifi", "ar_condicionado", "projetor"],
      local: "Recife",
      stars: 5,
      ar_condicionado: true,
      tv: false,
      wifi: true,
      petFriendly: false,
      cafeDaManha: false,
      estacionamento: true,
      avaliacao: 4.8,
    },
  ],
  [
    {
      id: "2",
      pf_id: "Jéssica",
      room_id: "102",
      check_in: new Date("2025-03-26"),
      check_out: new Date("2025-03-30"),
      guests: 2,
      total: 457.90,
      status: "Confirmada",
      rating: { stars: 4, comment: "Muito bom" },
    },
    {
      id: "102",
      pj_id: "PJ002",
      description: "CIn - Sala E122",
      type: "Padrão",
      price: 100,
      capacity: 20,
      caracteristics_ids: ["wifi", "tv"],
      local: "Recife",
      stars: 4,
      ar_condicionado: false,
      tv: true,
      wifi: true,
      petFriendly: false,
      cafeDaManha: false,
      estacionamento: false,
      avaliacao: 4.2,
    },
  ],
  [
    {
      id: "3",
      pf_id: "Jorge",
      room_id: "103",
      check_in: new Date("2025-04-04"),
      check_out: new Date("2025-04-12"),
      guests: 3,
      total: 1033.59,
      status: "Pendente",
      rating: { stars: 3, comment: "Aguardando confirmação" },
    },
    {
      id: "103",
      pj_id: "PJ003",
      description: "CIn - Sala E123",
      type: "Evento",
      price: 500,
      capacity: 100,
      caracteristics_ids: ["wifi", "ar_condicionado", "estacionamento"],
      local: "Recife",
      stars: 3,
      ar_condicionado: true,
      tv: false,
      wifi: true,
      petFriendly: false,
      cafeDaManha: false,
      estacionamento: true,
      avaliacao: 3.5,
    },
  ],
];

export function getLocationById(id: string): Room | undefined {
  return roomsFallbackData.find((location) => location.id === id)
}

export function getReservationsByLocationId(id: string): Reservation[] {
  return reservationFallbackData.filter((reservation2) => reservation2.id === id)
}

